# Generated by Django 5.2.4 on 2025-08-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginstore',
            old_name='product',
            new_name='message',
        ),
    ]
